config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }

  authenticated :user do
    root 'panel#dashboard'
  end

  unauthenticated :user do
    root 'static_pages#home'
  end

  get "browse/:id" => "folders#browse", :as => "browse"
  get "browse/:id/new_folder", to: "folders#new", as: "new_sub_folder"
  get "browse/:id/new_file", to: "assets#new", as: "new_sub_file"
  get "browse/:id/rename", to: "folders#edit", as: "rename_folder"
  post 'assets/download/:id', to: 'assets#download', as: 'download'
  get 'plan', to: 'panel#plan'
  get 'dashboard', to: 'panel#dashboard'
  get 'files', to: 'panel#files'
  get 'share/files', to: 'panel#share_files'
  get 'shared_assets/:asset_id/members', to: "shared_assets#members", as: "members"
  get 'terms', to: "static_pages#terms"
  get 'privacy_policy', to: "static_pages#privacy_policy"
  get 'contact', to: "static_pages#contact"
  get 'about', to: "static_pages#about_us"

  post "stripe/webhook", to: "stripe_webhook#action"

  resources :plans, only: [:index]
  resources :payments, only: [:show, :index]
  resources :subscriptions, path_names: { new: 'new/:plan_id' }

  resource :payment_method, only: [:edit, :update]

  resources :assets, except: [:index]
  resources :folders, except: [:index]
  resources :shared_assets, path_names: { new: 'new/:asset_id' }

  namespace :admin do
    resources :users do
      get 'statistics', to: "users#statistics"
    end
    resources :payments
  end

end

app/models/folder.rb
class Folder < ApplicationRecord
  acts_as_tree

  belongs_to :user
  has_many :assets, dependent: :destroy

  validates_presence_of :name
  validates_uniqueness_of :name, scope: [:parent_id, :user_id]

  def files_and_subfolders_count
    assets.count + children.count
  end

end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_folder, only: [:show, :edit, :update, :destroy, :browse]
  before_action :set_current_folder, only: [:new]

  layout 'panel'

  def show
    authorize! :show, @folder, message: "No tienes acceso a esta carpeta."
  end

  def new
    @folder = current_user.folders.build
    if params[:id]
      authorize! :new, @current_folder, message: "No tienes acceso a esta carpeta."
      @folder.parent_id = @current_folder.id
    end
  end

  def create
    @folder = current_user.folders.build(folder_params)
    if @folder.save
      flash[:notice] = "La carpeta se ha creado correctamente."
      if @folder.parent
        redirect_to browse_path(@folder.parent)
      else
        redirect_to files_path
      end
    else
      render :new
    end
  end

  def edit
    authorize! :edit, @folder, message: "No tienes acceso a esta carpeta."
  end

  def update
    authorize! :update, @folder, message: "No tienes acceso a esta carpeta."
    if @folder.update_attributes(folder_params)
      flash[:notice] = "La carpeta se ha renombrado correctamente."
      if @folder.parent
        redirect_to browse_path(@folder.parent)
      else
        redirect_to files_path
      end
    else
      render :edit
    end
  end

  def destroy
    authorize! :destroy, @folder, message: "No tienes acceso a esta carpeta."
    @parent_folder = @folder.parent
    if @folder.destroy
      flash[:notice] = "La carpeta y todo su contenido se han eliminado correctamente."
      if @parent_folder
        redirect_to browse_path(@parent_folder)
      else
        redirect_to files_path
      end
    end
  end

  def browse
    authorize! :browse, @folder, message: "No tienes acceso a esta carpeta."
    if @folder
      @subfolders = @folder.children
      @assets = @folder.assets
    end
  end

  private

    def folder_params
      params.require(:folder).permit(:name, :parent_id)
    end

    def set_folder
      @folder = Folder.find(params[:id])
    rescue
      redirect_to files_path, alert: "Esta carpeta no existe o ha sido eliminada."
    end

    def set_current_folder
      @current_folder = Folder.find(params[:id]) if params[:id]
    rescue
      redirect_to files_path, alert: "Esta carpeta no existe o ha sido eliminada."
    end

end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/views/folders/_back_link.html.erb
<%= link_to @folder.parent ? browse_path(@folder.parent) : files_path, class: "btn btn-light mt-2" do %>
  <i class="fas fa-arrow-left"></i> Atrás
<% end %>

app/views/folders/_folder_details.html.erb
<div class="card">
  <div class="card-header">
    Detalles de la carpeta
  </div>
  <div class="card-body">
    <ul class="list-unstyled"
      <li class="mt-2 mb-2">
        <span class="h6">Dueño:</span>
        <span class="float-right"><%= @folder.user.full_name %></span>
      </li>
      <li class="mt-2 mb-2">
        <span class="h6">Fecha de subida:</span>
        <span class="float-right"><%= l @folder.created_at.to_datetime, format: :short %></span>
      </li>
      <li class="mt-2 mb-2">
        <span class="h6">Ultima modificación:</span>
        <span class="float-right"><%= l @folder.updated_at.to_datetime, format: :short %></span>
      </li>
      <li class="mt-2 mb-2">
        <span class="h6">Tamaño:</span>
        <span class="float-right">-</span>
      </li>
      <li class="mt-2 mb-2">
        <span class="h6">Tipo:</span>
        <span class="float-right">Carpeta</span>
      </li>
      <li class="mt-2 mb-2">
        <span class="h6">Número de archivos:</span>
        <span class="float-right"><%= @folder.files_and_subfolders_count %></span>
      </li>
    </ul>
  </div>
</div>

app/views/folders/_form.html.erb
<%= form_for @folder do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <% if @folder.new_record? %>
    <div class="form-group">
      <%= f.label :name, "Nombre de la carpeta" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <%= f.hidden_field :parent_id %>
    <div class="form-group">
      <%= f.submit "Crear carpeta", class: "btn btn-block btn-primary" %>
    </div>
  <% else %>
    <div class="form-group">
      <%= f.label :name, "Nombre de la carpeta" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <%= f.hidden_field :parent_id %>
    <div class="form-group">
      <%= f.submit "Renombrar carpeta", class: "btn btn-block btn-primary" %>
    </div>
  <% end %>
<% end %>

app/views/folders/browse.html.erb
<% provide(:title, "Consultar carpeta") %>

<div id="wrapper">

  <ul class="sidebar navbar-nav">
    <li class="nav-item">
      <%= link_to dashboard_path, class: "nav-link" do %>
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Panel de control</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to files_path, class: "nav-link active" do %>
        <i class="fas fa-fw fa-folder-open"></i>
        <span>Mis archivos</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to share_files_path, class: "nav-link" do %>
        <i class="fas fa-fw fa-share-alt"></i>
        <span>Compartiendo conmigo</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to plan_path, class: "nav-link" do %>
        <i class="fas fa-fw fa-calendar"></i>
        <span>Mi plan</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to payments_path, class: "nav-link" do %>
        <i class="fas fa-fw fa-file-invoice"></i>
        <span>Historial de pagos</span>
      <% end %>
    </li>
    <% if current_user.admin? %>
      <li class="nav-item">
        <%= link_to "#", class: "nav-link" do %>
          <i class="fas fa-fw fa-chart-bar"></i>
          <span>Estadísticas del servicio</span>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to admin_users_path, class: "nav-link" do %>
          <i class="fas fa-fw fa-users"></i>
          <span>Usuarios</span>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to admin_payments_path, class: "nav-link" do %>
          <i class="fas fa-fw fa-file-invoice"></i>
          <span>Historial de pagos del servicio</span>
        <% end %>
      </li>
    <% end %>
  </ul>

  <div id="content-wrapper">

    <div class="container-fluid">
      <div class="row">
        <div class="col">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb bg-white breadcrumb-right-arrow">
              <% if @folder %>
                <li class="breadcrumb-item"><%= link_to "Mis archivos", files_path %></li>
                <% @folder.ancestors.reverse.each do |folder| %>
                  <li class="breadcrumb-item"><%= link_to folder.name, browse_path(folder) %></li>
                <% end %>
                <li class="breadcrumb-item active" aria-current="page"><%= @folder.name %></li>
              <% else %>
                <li class="breadcrumb-item active" aria-current="page">Mis archivos</li>
              <% end %>
            </ol>
          </nav>
        </div>
      </div>
      <div class="row pt-4 pb-4">
        <div class="col">
          <div class="float-right">
            <%= link_to new_sub_file_path(@folder), class: "btn btn-primary" do %>
              <i class="fas fa-file-upload mr-1"></i>
              Subir archivo
            <% end %>
            <%= link_to new_sub_folder_path, class: "btn btn-primary" do %>
              <i class="fas fa-folder-plus mr-1"></i>
              Nueva carpeta
            <% end %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <div class="card">
            <div class="card-body">
              <div class="table-responsive">
                <table class="table files">
                  <thead>
                    <tr>
                      <th scope="col"></th>
                      <th scope="col">Nombre</th>
                      <th scope="col">Fecha de subida</th>
                      <th scope="col">Tamaño</th>
                      <th scope="col">Miembros</th>
                      <th scope="col"></th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @subfolders.each do |folder| %>
                      <tr>
                        <th scope="row" class="align-middle"> <%= image_tag("fileicons/folder.png", size: '40x40') %> </th>
                        <td class="align-middle"> <%= link_to folder.name, browse_path(folder) %> </td>
                        <td class="align-middle"> <%= l folder.created_at.to_datetime, format: :short %> </td>
                        <td class="align-middle"> - </td>
                        <td class="align-middle"> Solo tú </td>
                        <td class="text-center align-middle">
                          <div class="dropdown">
                            <button class="btn" href="#" id="folderDropdown" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              <i class="fas fa-ellipsis-h"></i>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="folderDropdown">
                              <%= link_to folder, class: "dropdown-item" do %>
                                <i class="fas fa-info mr-1"></i> Detalles
                              <% end %>
                              <%= link_to rename_folder_path(folder), class: "dropdown-item" do %>
                                <i class="fas fa-edit mr-1"></i> Renombrar
                              <% end %>
                              <%= link_to "#", class: "dropdown-item" do %>
                                <i class="fas fa-share-alt mr-1"></i> Compartir
                              <% end %>
                              <%= link_to folder, class: "dropdown-item", method: :delete, data: {confirm: '¿Deseas eliminar esta carpeta y todo su contenido?'} do %>
                                <i class="fas fa-trash-alt mr-1"></i> Eliminar
                              <% end %>
                            </div>
                          </div>
                        </td>
                      </tr>
                    <% end %>
                    <% @assets.each do |asset| %>
                      <tr>
                        <th scope="row" class="align-middle"> <%= image_tag(file_icon(asset.uploaded_file.filename.extension), size: '40x40') %> </th>
                        <td class="align-middle"><%= link_to asset.uploaded_file.filename, asset %></td>
                        <td class="align-middle"><%= l asset.uploaded_file.created_at.to_datetime, format: :short %></td>
                        <td class="align-middle"><%= number_to_human_size(asset.uploaded_file.byte_size) %></td>
                        <td class="align-middle">
                          <% if asset.shared? %>
                            <%= asset.members_count %>
                          <% else %>
                            Solo tú
                          <% end %>
                        </td>
                        <td class="text-center align-middle">
                          <div class="dropdown">
                            <button class="btn" href="#" id="fileDropdown" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              <i class="fas fa-ellipsis-h"></i>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="fileDropdown">
                              <%= link_to asset, class: "dropdown-item" do %>
                                <i class="fas fa-info mr-1"></i> Detalles
                              <% end %>
                              <%= link_to edit_asset_path(asset), class: "dropdown-item" do %>
                                <i class="fas fa-edit mr-1"></i> Renombrar
                              <% end %>
                              <%= link_to download_path(asset), class: "dropdown-item", method: "post" do %>
                                <i class="fas fa-file-download mr-1"></i> Descargar
                              <% end %>
                              <%= link_to new_shared_asset_path(asset), class: "dropdown-item" do %>
                                <i class="fas fa-share-alt mr-1"></i> Comparte
                              <% end %>
                              <% if asset.shared? %>
                                <%= link_to members_path(asset), class: "dropdown-item" do %>
                                  <i class="fas fa-user mr-1"></i> Miembros
                                <% end %>
                              <% end %>
                              <%= link_to asset, class: "dropdown-item", method: :delete, data: {confirm: '¿Deseas eliminar este archivo?'} do %>
                                <i class="fas fa-trash-alt mr-1"></i> Eliminar
                              <% end %>
                            </div>
                          </div>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
          <br>
        </div>
      </div>

    </div>

    <%= render 'shared/panel_footer' %>

  </div>

</div>

app/views/folders/edit.html.erb
<% provide(:title, "Renombrar carpeta") %>

<div id="wrapper">

  <ul class="sidebar navbar-nav">
    <li class="nav-item">
      <%= link_to dashboard_path, class: "nav-link" do %>
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Panel de control</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to files_path, class: "nav-link active" do %>
        <i class="fas fa-fw fa-folder-open"></i>
        <span>Mis archivos</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to share_files_path, class: "nav-link" do %>
        <i class="fas fa-fw fa-share-alt"></i>
        <span>Compartiendo conmigo</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to plan_path, class: "nav-link" do %>
        <i class="fas fa-fw fa-calendar"></i>
        <span>Mi plan</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to payments_path, class: "nav-link" do %>
        <i class="fas fa-fw fa-file-invoice"></i>
        <span>Historial de pagos</span>
      <% end %>
    </li>
    <% if current_user.admin? %>
      <li class="nav-item">
        <%= link_to "#", class: "nav-link" do %>
          <i class="fas fa-fw fa-chart-bar"></i>
          <span>Estadísticas del servicio</span>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to admin_users_path, class: "nav-link" do %>
          <i class="fas fa-fw fa-users"></i>
          <span>Usuarios</span>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to admin_payments_path, class: "nav-link" do %>
          <i class="fas fa-fw fa-file-invoice"></i>
          <span>Historial de pagos del servicio</span>
        <% end %>
      </li>
    <% end %>
  </ul>

  <div id="content-wrapper">
    <div class="container-fluid">
      <div class="row">
        <div class="col">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb bg-white breadcrumb-right-arrow">
              <li class="breadcrumb-item"><%= link_to "Mis archivos", files_path %></li>
              <% if @folder.parent %>
                <li class="breadcrumb-item"><%= link_to @folder.parent.name, browse_path(@folder.parent) %></li>
              <% end %>
              <li class="breadcrumb-item active" aria-current="page">Renombrar carpeta</li>
            </ol>
          </nav>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6 col-lg-7 col-xl-8 mx-auto">
          <div class="card">
            <div class="card-header">Renombrar carpeta</div>
            <div class="card-body">
              <%= render 'form', folder: @folder %>
            </div>
          </div>
          <%= render 'back_link' %>
        </div>
      </div>
      <br>
    </div>
    <br>
    <%= render 'shared/panel_footer' %>

  </div>

</div>

app/views/folders/new.html.erb
<% provide(:title, "Nueva carpeta") %>

<div id="wrapper">

  <ul class="sidebar navbar-nav">
    <li class="nav-item">
      <%= link_to dashboard_path, class: "nav-link" do %>
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Panel de control</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to files_path, class: "nav-link active" do %>
        <i class="fas fa-fw fa-folder-open"></i>
        <span>Mis archivos</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to share_files_path, class: "nav-link" do %>
        <i class="fas fa-fw fa-share-alt"></i>
        <span>Compartiendo conmigo</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to plan_path, class: "nav-link" do %>
        <i class="fas fa-fw fa-calendar"></i>
        <span>Mi plan</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to payments_path, class: "nav-link" do %>
        <i class="fas fa-fw fa-file-invoice"></i>
        <span>Historial de pagos</span>
      <% end %>
    </li>
    <% if current_user.admin? %>
      <li class="nav-item">
        <%= link_to "#", class: "nav-link" do %>
          <i class="fas fa-fw fa-chart-bar"></i>
          <span>Estadísticas del servicio</span>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to admin_users_path, class: "nav-link" do %>
          <i class="fas fa-fw fa-users"></i>
          <span>Usuarios</span>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to admin_payments_path, class: "nav-link" do %>
          <i class="fas fa-fw fa-file-invoice"></i>
          <span>Historial de pagos del servicio</span>
        <% end %>
      </li>
    <% end %>
  </ul>

  <div id="content-wrapper">
    <div class="container-fluid">
      <div class="row">
        <div class="col">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb bg-white breadcrumb-right-arrow">
              <li class="breadcrumb-item"><%= link_to "Mis archivos", files_path %></li>
              <% if @folder.parent %>
                <li class="breadcrumb-item"><%= link_to @folder.parent.name, browse_path(@folder.parent) %></li>
              <% end %>
              <li class="breadcrumb-item active" aria-current="page">Crear carpeta</li>
            </ol>
          </nav>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6 col-lg-7 col-xl-8 mx-auto">
          <div class="card">
            <div class="card-header">Crear carpeta</div>
            <div class="card-body">
              <%= render 'form', folder: @folder %>
            </div>
          </div>
          <%= render 'back_link' %>
        </div>
      </div>
      <br>
    </div>
    <br>
    <%= render 'shared/panel_footer' %>

  </div>

</div>

app/views/folders/show.html.erb
<% provide(:title, "Detalles de la carpeta") %>

<div id="wrapper">

  <ul class="sidebar navbar-nav">
    <li class="nav-item">
      <%= link_to dashboard_path, class: "nav-link" do %>
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Panel de control</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to files_path, class: "nav-link active" do %>
        <i class="fas fa-fw fa-folder-open"></i>
        <span>Mis archivos</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to share_files_path, class: "nav-link" do %>
        <i class="fas fa-fw fa-share-alt"></i>
        <span>Compartiendo conmigo</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to plan_path, class: "nav-link" do %>
        <i class="fas fa-fw fa-calendar"></i>
        <span>Mi plan</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to payments_path, class: "nav-link" do %>
        <i class="fas fa-fw fa-file-invoice"></i>
        <span>Historial de pagos</span>
      <% end %>
    </li>
    <% if current_user.admin? %>
      <li class="nav-item">
        <%= link_to "#", class: "nav-link" do %>
          <i class="fas fa-fw fa-chart-bar"></i>
          <span>Estadísticas del servicio</span>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to admin_users_path, class: "nav-link" do %>
          <i class="fas fa-fw fa-users"></i>
          <span>Usuarios</span>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to admin_payments_path, class: "nav-link" do %>
          <i class="fas fa-fw fa-file-invoice"></i>
          <span>Historial de pagos del servicio</span>
        <% end %>
      </li>
    <% end %>
  </ul>

  <div id="content-wrapper">
    <div class="container-fluid">
      <div class="row">
        <div class="col">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb bg-white breadcrumb-right-arrow">
              <li class="breadcrumb-item"><%= link_to "Mis archivos", files_path %></li>
              <% if @folder.parent %>
                <li class="breadcrumb-item"><%= link_to @folder.parent.name, browse_path(@folder.parent) %></li>
              <% end %>
              <li class="breadcrumb-item active" aria-current="page">Detalles de carpeta</li>
            </ol>
          </nav>
        </div>
      </div>
      <div class="row">
        <div class="col-md-7 col-lg-8 col-xl-9 mx-auto">
          <div class="card">
            <div class="card-header"><%= @folder.name %></div>
            <div class="card-body">
              <div class="row">
                <div class="col align-self-center text-center">
                    <div>
                      <span>No hay vista previa para esta carpeta.</span>
                    </div>
                </div>
                <div class="col">
                  <%= render 'folder_details', folder: @folder %>
                </div>
              </div>
            </div>
          </div>
          <%= render 'back_link' %>
        </div>
      </div>
      <br>
    </div>
    <br>
    <%= render 'shared/panel_footer' %>

  </div>

</div>