config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }

  authenticated :user do
    root 'panel#dashboard'
  end

  unauthenticated :user do
    root 'static_pages#home'
  end

  get "browse/:id" => "folders#browse", :as => "browse"
  get "browse/:id/new_folder", to: "folders#new", as: "new_sub_folder"
  get "browse/:id/new_file", to: "assets#new", as: "new_sub_file"
  get "browse/:id/rename", to: "folders#edit", as: "rename_folder"
  post 'assets/download/:id', to: 'assets#download', as: 'download'
  get 'plan', to: 'panel#plan'
  get 'dashboard', to: 'panel#dashboard'
  get 'files', to: 'panel#files'
  get 'share/files', to: 'panel#share_files'
  get 'shared_assets/:asset_id/members', to: "shared_assets#members", as: "members"
  get 'terms', to: "static_pages#terms"
  get 'privacy_policy', to: "static_pages#privacy_policy"
  get 'contact', to: "static_pages#contact"
  get 'about', to: "static_pages#about_us"

  post "stripe/webhook", to: "stripe_webhook#action"

  resources :plans, only: [:index]
  resources :payments, only: [:show, :index]
  resources :subscriptions, path_names: { new: 'new/:plan_id' }

  resource :payment_method, only: [:edit, :update]

  resources :assets, except: [:index]
  resources :folders, except: [:index]
  resources :shared_assets, path_names: { new: 'new/:asset_id' }

  namespace :admin do
    resources :users do
      get 'statistics', to: "users#statistics"
    end
    resources :payments
  end

end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :plan

  has_one :payment_line_item, as: :buyable

  validates_presence_of :type

  enum status: {active: 0, inactive: 1,
                waiting: 2, pending_initial_payment: 3,
                canceled: 4}

  delegate :name, to: :plan

  scope :free_subscription, -> { where(type: 'FreeSubscription') }
  scope :paid_subscription, -> { where(type: 'PaidSubscription' ) }

  def free?
    type == 'FreeSubscription'
  end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit]
  before_action :check_edit_subscription, only: [:edit]
  before_action :check_new_subscription, only: [:new]
  before_action :set_selected_plan, only: [:new, :create]

  def new
  end

  def create
    workflow = stripe_subscription_workflow
    if workflow.success
      redirect_to root_path, notice: "Te has suscrito exitosamente al plan #{@selected_plan.name}"
    else
      redirect_to new_subscription_path(@selected_plan.id), alert: workflow.error_message
    end
  end

  def edit
    @monthly_paid_plans = PaidPlan.active.month.where.not(id: params[:id])
    @yearly_paid_plans = PaidPlan.active.year.where.not(id: params[:id])
  end

  def update
    workflow = ChangesStripeSubscriptionPlan.new(
        subscription_id: current_user.current_subscription.id,
        user: current_user,
        new_plan_id: params[:new_plan_id])
    workflow.run
    if workflow.success
      redirect_to plan_path, notice: "Tu subscripción ha sido cambiada correctamente."
    else
      redirect_to plan_path, alert: "Ha ocurrido un error al cambiar tu suscripción."
    end
  end

  def destroy
    workflow = CancelsStripeSubscription.new(
        subscription_id: params[:id],
        user: current_user)
    workflow.run
    if workflow.success
      redirect_to plan_path, notice: "Su suscripción ha sido cancelada con éxito."
    else
      redirect_to plan_path, alert: "Ha ocurrido un problema al cancelar su suscripción."
    end
  end

  private

    def stripe_subscription_workflow
      workflow = CreatesSubscriptionViaStripe.new(
          user: current_user,
          plan: @selected_plan,
          token: StripeToken.new(**card_params))
      workflow.run
      workflow
    end

    def card_params
      params.permit(
          :credit_card_number, :expiration_month,
          :expiration_year, :cvc,
          :stripe_token).to_h.symbolize_keys
    end

    def set_selected_plan
      @selected_plan = Plan.find(params[:plan_id])
    end

    def check_edit_subscription
      if current_user.current_subscription.free?
        flash[:alert] = "Debes estar suscrito a un plan de pago para cambiarla."
        redirect_back(fallback_location: root_path)
      end
    end

    def check_new_subscription
      unless current_user.current_subscription.free?
        flash[:alert] = "Ya se encuentra suscrito a una suscripción de pago."
        redirect_back(fallback_location: root_path)
      end
    end

end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_monthly_paid_plan.html.erb
<div class="col-4 mx-auto">
  <div class="card mb-4 box-shadow">
    <div class="card-header">
      <h4 class="my-0 font-weight-normal"><%= monthly_paid_plan.name %></h4>
    </div>
    <div class="card-body">
      <%= image_tag("#{monthly_paid_plan.name.downcase}.png", alt: "#{monthly_paid_plan.name}_icon") %>
      <h1 class="card-title pricing-card-title">
        <%= humanized_money(monthly_paid_plan.price) %> &euro;<small class="text-muted">/mes</small>
      </h1>
      <ul class="list-unstyled mt-3 mb-4">
        <li><%= monthly_paid_plan.space_allowed %> GB de almacenamiento</li>
        <li><br></li>
        <li><br></li>
        <li><br></li>
      </ul>
      <%= form_tag(subscription_path, method: :patch) do %>
        <%= hidden_field_tag(:new_plan_id, monthly_paid_plan.id) %>
        <%= submit_tag("Cambiar", class: "btn btn-lg btn-block btn-outline-primary") %>
      <% end %>
    </div>
  </div>
</div>

app/views/subscriptions/_yearly_paid_plan.html.erb
<div class="col-4 mr-auto ml-auto">
  <div class="card mb-4 box-shadow">
    <div class="card-header">
      <h4 class="my-0 font-weight-normal"><%= yearly_paid_plan.name %></h4>
    </div>
    <div class="card-body">
      <%= image_tag("#{yearly_paid_plan.name.downcase}.png", alt: "#{yearly_paid_plan.name}_icon") %>
      <h1 class="card-title pricing-card-title">
        <%= humanized_money(yearly_paid_plan.price) %> &euro;<small class="text-muted">/año</small>
      </h1>
      <ul class="list-unstyled mt-3 mb-4">
        <li><%= yearly_paid_plan.space_allowed %> GB de almacenamiento</li>
        <li><br></li>
        <li><br></li>
        <li><br></li>
      </ul>
      <%= form_tag(subscription_path, method: :patch) do %>
        <%= hidden_field_tag(:new_plan_id, yearly_paid_plan.id) %>
        <%= submit_tag("Cambiar", class: "btn btn-lg btn-block btn-outline-primary") %>
      <% end %>
    </div>
  </div>
</div>

app/views/subscriptions/edit.html.erb
<% provide(:title, "Cambiar suscripción") %>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">Planes disponibles</h1>
  <p class="lead">Elije el que quieras para cambiar tu suscripción</p>
</div>

<div class="container">
  <div class="row">
    <div class="col offset-5">
      <ul class="nav nav-pills" role="tablist">
        <li class="nav-item">
          <a class="nav-link active" data-toggle="pill" href="#monthly">Mensual</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-toggle="pill" href="#yearly">Anual</a>
        </li>
      </ul>
    </div>
  </div>
  <div class="tab-content">
    <div id="monthly" class="container tab-pane active"><br>
      <div class="row card-deck mb-3 text-center">
        <%= render partial: "subscriptions/monthly_paid_plan", collection: @monthly_paid_plans %>
      </div>
    </div>
    <div id="yearly" class="container tab-pane fade"><br>
      <div class="row card-deck mb-3 text-center">
        <%= render partial: "subscriptions/yearly_paid_plan", collection: @yearly_paid_plans %>
      </div>
    </div>
  </div>

</div>

app/views/subscriptions/new.html.erb
<% provide(:title, "Adquirir suscripción") %>

<div class="container p-5">
  <div class="row">
    <div class="col-4 ml-auto mr-auto">
      <div class="card-deck mb-3 text-center">
        <% if @selected_plan.month? %>
          <p>Has seleccionado el plan <%= @selected_plan.name %> con ciclo de facturación mensual</p>
        <% else %>
          <p>Has seleccionado el plan <%= @selected_plan.name %> con ciclo de facturación anual</p>
        <% end %>
      </div>
      <div class="text-center">
        <button type="button" class="btn btn-info" data-toggle="modal" data-target="#paymentInfo">
          <i class="fas fa-credit-card"></i> Información de pago
        </button>
      </div>
    </div>
    <div class="col-6 ml-auto mr-auto">
      <div id="payment-form-card-errors" class="alert-danger alert d-none" role="alert"></div>
      <div class="card">
        <div class="card-body">
          <div>
            <h5 class="card-title">Formulario de pago</h5>
            <hr>
          </div>
          <%= form_tag(subscriptions_path, id: "payment-form") do %>
          <%= hidden_field_tag(:purchase_amounts_cents, @selected_plan.price_cents) %>
          <%= hidden_field_tag(:plan_id, @selected_plan.id) %>
          <div class="form-group">
            <%= content_tag(:div, nil , class: "form-control stripe-form-card", id: "payment-form-card") %>
          </div>
          <div class="form-group">
            <%= submit_tag("Comprar suscripción", class: "btn btn-block btn-primary", id: "payment-submit", data: { disable_with: false }) %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="modal" id="paymentInfo">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Datos de pago</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <h6>Números de tarjeta de crédito válidos</h6>
        <hr>
        <p><span class="font-weight-bold">Visa: </span> 4242 4242 4242 4242</p>
        <p><span class="font-weight-bold">Mastercard: </span> 4000 0566 5566 5556</p>
        <p><span class="font-weight-bold">American Express: </span> 3782 822463 10005</p>
        <p><span class="font-weight-bold">American Express: </span> 3714 496353 98431</p>
        <p><span class="font-weight-bold">Discover: </span> 6011 1111 1111 1117</p>
        <p><span class="font-weight-bold">Discover: </span> 6011 0009 9013 9424</p>
        <p><span class="font-weight-bold">Diners Club: </span> 3056 9309 0259 04</p>
        <p><span class="font-weight-bold">Diners Club: </span> 3852 0000 0232 37</p>
        <h6>Números de tarjeta de crédito inválidos</h6>
        <hr>
        <p><span class="font-weight-bold">Tarjeta rechazada: </span> 4000 0000 0000 0002</p>
        <p><span class="font-weight-bold">Tarjeta caducada: </span> 4000 0000 0000 0069</p>
        <p><span class="font-weight-bold">Código de seguridad incorrecto: </span> 4000 0000 0000 0127</p>
        <p><span class="font-weight-bold">Error de procesamiento: </span> 4000 0000 0000 0119</p>
        <p><span class="font-weight-bold">Número de tarjeta incorrecto: </span> 4242 4242 4242 4241</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>