config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }

  authenticated :user do
    root 'panel#dashboard'
  end

  unauthenticated :user do
    root 'static_pages#home'
  end

  get "browse/:id" => "folders#browse", :as => "browse"
  get "browse/:id/new_folder", to: "folders#new", as: "new_sub_folder"
  get "browse/:id/new_file", to: "assets#new", as: "new_sub_file"
  get "browse/:id/rename", to: "folders#edit", as: "rename_folder"
  post 'assets/download/:id', to: 'assets#download', as: 'download'
  get 'plan', to: 'panel#plan'
  get 'dashboard', to: 'panel#dashboard'
  get 'files', to: 'panel#files'
  get 'share/files', to: 'panel#share_files'
  get 'shared_assets/:asset_id/members', to: "shared_assets#members", as: "members"
  get 'terms', to: "static_pages#terms"
  get 'privacy_policy', to: "static_pages#privacy_policy"
  get 'contact', to: "static_pages#contact"
  get 'about', to: "static_pages#about_us"

  post "stripe/webhook", to: "stripe_webhook#action"

  resources :plans, only: [:index]
  resources :payments, only: [:show, :index]
  resources :subscriptions, path_names: { new: 'new/:plan_id' }

  resource :payment_method, only: [:edit, :update]

  resources :assets, except: [:index]
  resources :folders, except: [:index]
  resources :shared_assets, path_names: { new: 'new/:asset_id' }

  namespace :admin do
    resources :users do
      get 'statistics', to: "users#statistics"
    end
    resources :payments
  end

end

app/models/user.rb
class User < ApplicationRecord
  after_create :create_free_subscription
  after_create :check_and_assign_shared_ids_to_shared_assets

  mount_uploader :avatar, AvatarUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

 	validates :name, presence: true
 	validates :last_name, presence: true
  validates_integrity_of :avatar
  validates_processing_of :avatar
  validate :avatar_size

  has_many :subscriptions, dependent: :destroy
  has_many :payments
  has_many :assets, dependent: :destroy
  has_many :folders, dependent: :destroy
  has_many :shared_assets, dependent: :destroy
  has_many :being_shared_assets, class_name: "SharedAsset", foreign_key: "shared_user_id", dependent: :destroy
  has_many :shared_assets_by_others, :through => :being_shared_assets, :source => :asset
  has_many :shared_assets_with_others, -> { distinct }, through: :shared_assets, source: :asset, dependent: :destroy

  def free_subscription
    subscriptions.where(type: "FreeSubscription").first
  end

  def current_subscription
    subscriptions.where(status: "active").last
  end

  def current_plan?(plan_id)
    current_subscription.plan.id == plan_id
  end

  def full_name
    "#{name} #{last_name}"
  end

  def payment_method?
    card_last4.present?
  end

  def available_storage_space
    total_storage_space - used_storage_space
  end

  def used_storage_space
    total_file_size = 0
    self.assets.each do |asset|
      total_file_size += asset.uploaded_file.byte_size
    end
    total_file_size
  end

  def total_storage_space
    current_subscription.plan.space_allowed.gigabyte
  end

  def percentage_used_storage_space
    (used_storage_space.to_f / total_storage_space.to_f) * 100
  end

  def has_available_storage_space?(file_byte_size)
    used_storage_space + file_byte_size < total_storage_space
  end

  def files_count
    self.assets.count
  end

  def folders_count
    self.folders.count
  end

  def shared_files_count
    self.shared_assets_with_others.count
  end

  private

    def avatar_size
      if avatar.size > 5.megabytes
        errors.add(:avatar, "debería ser menor de 5 megabytes")
      end
    end

    def create_free_subscription
      self.subscriptions.create!(plan: Plan.free_plan.first, status: 0,
          type: 'FreeSubscription')
    end

    def check_and_assign_shared_ids_to_shared_assets
      shared_assets_with_same_email = SharedAsset.where(shared_email: self.email)
      if shared_assets_with_same_email
        shared_assets_with_same_email.each do |shared_asset|
          shared_asset.shared_user_id = self.id
          shared_asset.save
        end
      end
    end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  before_action :set_user, only: [:show, :destroy, :statistics]

  def index
    @users = User.where(admin: false)
  end

  def show
  end

  def destroy
    workflow = DeleteUser.new(subscription_id: @user.current_subscription.id, user: @user)
    workflow.run
    if workflow.success
      redirect_to admin_users_path, notice: "El usuario ha sido eliminado correctamente."
    else
      redirect_to admin_users_path, alert: "Ha ocurrido un error al intentar eliminar el usuario."
    end
  end

  def statistics
  end

  private

    def set_user
      @user = User.find(params[:id] || params[:user_id])
    rescue
      redirect_to admin_users_path, alert: "Este usuario no existe o ya ha sido eliminado."
    end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_user_statistics.html.erb
<div class="card">
  <div class="card-header">Estadísticas del usuario</div>
  <div class="card-body">
    <div class="row">
      <div class="col">
        <h6>Archivos subidos</h6>
        <div>
          <%= @user.uploaded_files_count %>
        </div>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col">
        <h6>Archivos descargados</h6>
        <div>
          <%= @user.downloaded_files_count %>
        </div>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col">
        <h6>Archivos compartidos</h6>
        <div>
          <%= @user.shared_files_count %>
        </div>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col">
        <h6>Archivos</h6>
        <div>
          <%= @user.files_count %>
        </div>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col">
        <h6>Carpetas</h6>
        <div>
          <%= @user.folders_count %>
        </div>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col">
        <h6>Espacio de almacenamiento usado</h6>
        <div>
          <%= number_to_human_size(@user.used_storage_space) %>
        </div>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col">
        <h6>Espacio de almacenamiento disponible</h6>
        <div>
          <%= number_to_human_size(@user.available_storage_space) %>
        </div>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col">
        <h6>Espacio de almacenamiento total</h6>
        <div>
          <%= number_to_human_size(@user.total_storage_space) %>
        </div>
      </div>
    </div>
    <hr>
  </div>
</div>

app/views/admin/users/_users_table.html.erb
<div class="card">
  <div class="card-body">
    <div class="table-responsive">
      <table id="users" class="table">
        <thead>
          <tr>
            <th scope="col">Avatar</th>
            <th scope="col">Nombre</th>
            <th scope="col">Apellidos</th>
            <th scope="col">Email</th>
            <th scope="col">Fecha de registro</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <th scope="row" class="align-middle"> <%= image_tag(user.avatar.url, size: '40x40') %> </th>
              <td class="align-middle"><%= user.name %></td>
              <td class="align-middle"><%= user.last_name %></td>
              <td class="align-middle"><%= user.email %></td>
              <td class="align-middle"><%= l user.created_at.to_datetime, format: :short %></td>
              <td class="text-center align-middle">
                <div class="dropdown">
                  <button class="btn" href="#" id="usersDropdown" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-ellipsis-h"></i>
                  </button>
                  <div class="dropdown-menu" aria-labelledby="usersDropdown">
                    <%= link_to admin_user_path(user), class: "dropdown-item" do %>
                      <i class="fas fa-info mr-1"></i> Detalles
                    <% end %>
                    <%= link_to admin_user_statistics_path(user), class: "dropdown-item" do %>
                      <i class="fas fa-chart-bar mr-1"></i> Estadísticas
                    <% end %>
                    <%= link_to admin_user_path(user), class: "dropdown-item", method: :delete, data: {confirm: '¿Deseas eliminar a este usuario?'} do %>
                      <i class="fas fa-trash-alt mr-1"></i> Eliminar
                    <% end %>
                  </div>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<br>

app/views/admin/users/index.html.erb
<% provide(:title, "Usuarios") %>

<div id="wrapper">

  <ul class="sidebar navbar-nav">
    <li class="nav-item">
      <%= link_to dashboard_path, class: "nav-link" do %>
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Panel de control</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to files_path, class: "nav-link" do %>
        <i class="fas fa-fw fa-folder-open"></i>
        <span>Mis archivos</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to share_files_path, class: "nav-link" do %>
        <i class="fas fa-fw fa-share-alt"></i>
        <span>Compartiendo conmigo</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to plan_path, class: "nav-link" do %>
        <i class="fas fa-fw fa-calendar"></i>
        <span>Mi plan</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to payments_path, class: "nav-link" do %>
        <i class="fas fa-fw fa-file-invoice"></i>
        <span>Historial de pagos</span>
      <% end %>
    </li>
    <% if current_user.admin? %>
      <li class="nav-item">
        <%= link_to "#", class: "nav-link" do %>
          <i class="fas fa-fw fa-chart-bar"></i>
          <span>Estadísticas del servicio</span>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to admin_users_path, class: "nav-link active" do %>
          <i class="fas fa-fw fa-users"></i>
          <span>Usuarios</span>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to admin_payments_path, class: "nav-link" do %>
          <i class="fas fa-fw fa-file-invoice"></i>
          <span>Historial de pagos del servicio</span>
        <% end %>
      </li>
    <% end %>
  </ul>

  <div id="content-wrapper">

    <div class="container-fluid">
      <div class="row">
        <div class="col">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb bg-white breadcrumb-right-arrow">
              <li class="breadcrumb-item active" aria-current="page">Usuarios</li>
            </ol>
          </nav>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <%= render partial: "users_table", users: @users %>
        </div>
      </div>

    </div>

    <%= render 'shared/panel_footer' %>

  </div>

</div>

app/views/admin/users/show.html.erb
<% provide(:title, "Usuario") %>

<div id="wrapper">

  <ul class="sidebar navbar-nav">
    <li class="nav-item">
      <%= link_to dashboard_path, class: "nav-link" do %>
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Panel de control</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to files_path, class: "nav-link" do %>
        <i class="fas fa-fw fa-folder-open"></i>
        <span>Mis archivos</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to share_files_path, class: "nav-link" do %>
        <i class="fas fa-fw fa-share-alt"></i>
        <span>Compartiendo conmigo</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to plan_path, class: "nav-link" do %>
        <i class="fas fa-fw fa-calendar"></i>
        <span>Mi plan</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to payments_path, class: "nav-link" do %>
        <i class="fas fa-fw fa-file-invoice"></i>
        <span>Historial de pagos</span>
      <% end %>
    </li>
    <% if current_user.admin? %>
      <li class="nav-item">
        <%= link_to "#", class: "nav-link" do %>
          <i class="fas fa-fw fa-chart-bar"></i>
          <span>Estadísticas del servicio</span>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to admin_users_path, class: "nav-link active" do %>
          <i class="fas fa-fw fa-users"></i>
          <span>Usuarios</span>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to admin_payments_path, class: "nav-link" do %>
          <i class="fas fa-fw fa-file-invoice"></i>
          <span>Historial de pagos del servicio</span>
        <% end %>
      </li>
    <% end %>
  </ul>

  <div id="content-wrapper">

    <div class="container-fluid">
      <div class="row">
        <div class="col">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb bg-white breadcrumb-right-arrow">
              <li class="breadcrumb-item"><%= link_to "Usuarios", admin_users_path %></li>
              <li class="breadcrumb-item active" aria-current="page"><%= @user.full_name %></li>
            </ol>
          </nav>
        </div>
      </div>
      <div class="row">
        <div class="col-md-5 col-lg-6 col-xl-7 mx-auto">
          <div class="card">
            <div class="card-header">Detalles del usuario</div>
            <div class="card-body">
              <div class="row">
                <div class="col">
                  <h6>Avatar</h6>
                  <div>
                    <%= image_tag(@user.avatar.url, size: '150x150', class: "img-thumbnail" ) %>
                  </div>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col">
                  <h6>Nombre</h6>
                  <div>
                    <%= @user.name %>
                  </div>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col">
                  <h6>Apellidos</h6>
                  <div>
                    <%= @user.last_name %>
                  </div>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col">
                  <h6>Email</h6>
                  <div>
                    <%= @user.email %>
                  </div>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col">
                  <h6>Fecha de registro</h6>
                  <div>
                    <%= l @user.created_at.to_datetime, format: :short %>
                  </div>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col">
                  <h6>Fecha de actualización</h6>
                  <div>
                    <%= l @user.updated_at.to_datetime, format: :short %>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <%= link_to :back, class: "btn btn-light mt-2" do %>
            <i class="fas fa-arrow-left"></i> Atrás
          <% end %>
        </div>
      </div>
      <br>
    </div>

    <%= render 'shared/panel_footer' %>

  </div>

</div>

app/views/admin/users/statistics.html.erb
<% provide(:title, "Usuario") %>

<div id="wrapper">

  <ul class="sidebar navbar-nav">
    <li class="nav-item">
      <%= link_to dashboard_path, class: "nav-link" do %>
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Panel de control</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to files_path, class: "nav-link" do %>
        <i class="fas fa-fw fa-folder-open"></i>
        <span>Mis archivos</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to share_files_path, class: "nav-link" do %>
        <i class="fas fa-fw fa-share-alt"></i>
        <span>Compartiendo conmigo</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to plan_path, class: "nav-link" do %>
        <i class="fas fa-fw fa-calendar"></i>
        <span>Mi plan</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to payments_path, class: "nav-link" do %>
        <i class="fas fa-fw fa-file-invoice"></i>
        <span>Historial de pagos</span>
      <% end %>
    </li>
    <% if current_user.admin? %>
      <li class="nav-item">
        <%= link_to "#", class: "nav-link" do %>
          <i class="fas fa-fw fa-chart-bar"></i>
          <span>Estadísticas del servicio</span>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to admin_users_path, class: "nav-link active" do %>
          <i class="fas fa-fw fa-users"></i>
          <span>Usuarios</span>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to admin_payments_path, class: "nav-link" do %>
          <i class="fas fa-fw fa-file-invoice"></i>
          <span>Historial de pagos del servicio</span>
        <% end %>
      </li>
    <% end %>
  </ul>

  <div id="content-wrapper">

    <div class="container-fluid">
      <div class="row">
        <div class="col">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb bg-white breadcrumb-right-arrow">
              <li class="breadcrumb-item"><%= link_to "Usuarios", admin_users_path %></li>
              <li class="breadcrumb-item active" aria-current="page"><%= @user.full_name %></li>
            </ol>
          </nav>
        </div>
      </div>
      <div class="row">
        <div class="col-md-5 col-lg-6 col-xl-7 mx-auto">
          <div class="card">
            <div class="card-header">Tipo de cuenta</div>
            <div class="card-body">
              <div class="row">
                <div class="col">
                  <h6>Plan</h6>
                  <div>
                    <%= @user.current_subscription.name %>
                  </div>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col">
                  <h6>Estado</h6>
                  <p><span class="badge badge-success"><%= t(".text.status.#{@user.current_subscription.status}") %></span></p>
                  <% unless @user.current_subscription.free? %>
                    <p>Su suscripción finalizará el <%= l @user.current_subscription.end_date, format: :default %>.</p>
                  <% end %>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col">
                  <h6>Espacio de almacenamiento</h6>
                  <span class="float-left"><%= number_to_percentage(@user.percentage_used_storage_space, precision: 0) %></span>
                  <p class="text-right font-weight-light">
                    <span class="font-weight-bold">
                      <%= @user.used_storage_space %> Bytes
                    </span>
                    de <%= @user.total_storage_space %> Bytes en uso
                  </p>
                  <div class="progress">
                    <div class="progress-bar" role="progressbar" style="width: <%=current_user.percentage_used_storage_space%>%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col">
                  <h6>Renovación</h6>
                  <% if @user.current_subscription.free? %>
                    <p>Sin ciclo de facturación</p>
                  <% else %>
                    <% if @user.current_subscription.plan.month? %>
                      <p>Mensual</p>
                    <% else %>
                      <p>Anual</p>
                    <% end %>
                  <% end %>
                </div>
              </div>
              <hr>
            </div>
          </div>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-md-5 col-lg-6 col-xl-7 mx-auto">
          <%= render "user_statistics", user: @user %>
          <%= link_to :back, class: "btn btn-light mt-2" do %>
            <i class="fas fa-arrow-left"></i> Atrás
          <% end %>
        </div>
      </div>
      <br>
    </div>

    <%= render 'shared/panel_footer' %>

  </div>

</div>