config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }

  authenticated :user do
    root 'panel#dashboard'
  end

  unauthenticated :user do
    root 'static_pages#home'
  end

  get "browse/:id" => "folders#browse", :as => "browse"
  get "browse/:id/new_folder", to: "folders#new", as: "new_sub_folder"
  get "browse/:id/new_file", to: "assets#new", as: "new_sub_file"
  get "browse/:id/rename", to: "folders#edit", as: "rename_folder"
  post 'assets/download/:id', to: 'assets#download', as: 'download'
  get 'plan', to: 'panel#plan'
  get 'dashboard', to: 'panel#dashboard'
  get 'files', to: 'panel#files'
  get 'share/files', to: 'panel#share_files'
  get 'shared_assets/:asset_id/members', to: "shared_assets#members", as: "members"
  get 'terms', to: "static_pages#terms"
  get 'privacy_policy', to: "static_pages#privacy_policy"
  get 'contact', to: "static_pages#contact"
  get 'about', to: "static_pages#about_us"

  post "stripe/webhook", to: "stripe_webhook#action"

  resources :plans, only: [:index]
  resources :payments, only: [:show, :index]
  resources :subscriptions, path_names: { new: 'new/:plan_id' }

  resource :payment_method, only: [:edit, :update]

  resources :assets, except: [:index]
  resources :folders, except: [:index]
  resources :shared_assets, path_names: { new: 'new/:asset_id' }

  namespace :admin do
    resources :users do
      get 'statistics', to: "users#statistics"
    end
    resources :payments
  end

end

app/models/plan.rb
class Plan < ApplicationRecord
  has_many :subscriptions

  enum status: {inactive: 0, active: 1}

  validates_presence_of :name
  validates_presence_of :type

  scope :free_plan, -> { where(type: 'FreePlan') }
  scope :paid_plan, -> { where(type: 'PaidPlan') }

end

app/controllers/plans_controller.rb
class PlansController < ApplicationController

  def index
    @free_plan = FreePlan.first
    @monthly_paid_plans = PaidPlan.active.month.all
    @yearly_paid_plans = PaidPlan.active.year.all
  end

end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_free_plan.html.erb
<div class="col-4 mx-auto">
  <div class="card mb-4 box-shadow">
    <div class="card-header">
      <h4 class="my-0 font-weight-normal"><%= free_plan.name %></h4>
    </div>
    <div class="card-body">
      <%= image_tag("#{free_plan.name.downcase}.png", alt: "#{free_plan.name}_icon") %>
      <h1 class="card-title pricing-card-title">
        0 &euro;<small class="text-muted"></small>
      </h1>
      <ul class="list-unstyled mt-3 mb-4">
        <li><%= free_plan.space_allowed %> GB de almacenamiento</li>
        <li><br></li>
        <li><br></li>
        <li><br></li>
      </ul>
      <% if user_signed_in? %>
        <% if current_user.current_subscription.free? %>
          <%= link_to "Estás suscrito", "#", class: "btn btn-lg btn-block btn-outline-primary disabled" %>
          <% else %>
            <%= link_to "No estás suscrito", "#", class: "btn btn-lg btn-block btn-outline-primary disabled" %>
          <% end %>
      <% else %>
        <%= link_to "Suscribirte", new_user_session_path, class: "btn btn-lg btn-block btn-outline-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/plans/_monthly_paid_plan.html.erb
<div class="col-4 mx-auto">
  <div class="card mb-4 box-shadow">
    <div class="card-header">
      <h4 class="my-0 font-weight-normal"><%= monthly_paid_plan.name %></h4>
    </div>
    <div class="card-body">
      <%= image_tag("#{monthly_paid_plan.name.downcase}.png", alt: "#{monthly_paid_plan.name}_icon") %>
      <h1 class="card-title pricing-card-title">
        <%= humanized_money(monthly_paid_plan.price) %> &euro;<small class="text-muted">/mes</small>
      </h1>
      <ul class="list-unstyled mt-3 mb-4">
        <li><%= monthly_paid_plan.space_allowed %> GB de almacenamiento</li>
        <li><br></li>
        <li><br></li>
        <li><br></li>
      </ul>
      <% if user_signed_in? %>
        <% if current_user.current_subscription.free? %>
          <%= link_to "Suscribirte", new_subscription_path(monthly_paid_plan.id), class: "btn btn-lg btn-block btn-outline-primary" %>
        <% else %>
          <% if current_user.current_plan?(monthly_paid_plan.id) %>
            <%= link_to "Estás suscrito", "#", class: "btn btn-lg btn-block btn-outline-primary disabled" %>
          <% else %>
            <%= link_to "No estás suscrito", "#", class: "btn btn-lg btn-block btn-outline-primary disabled" %>
          <% end %>
        <% end %>
      <% else %>
        <%= link_to "Suscribirte", new_user_session_path, class: "btn btn-lg btn-block btn-outline-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/plans/_plan.html.erb
<div class="card mb-4 box-shadow">
  <div class="card-header">
    <h4 class="my-0 font-weight-normal"><%= plan.name %></h4>
  </div>
  <div class="card-body">
    <%= image_tag(plan.name.downcase, alt: "#{plan.name}_icon") %>
    <h1 class="card-title pricing-card-title">
      <%= humanized_money(plan.price) %> &euro;<small class="text-muted">/ <%= t('pages.pricing.month') %></small>
    </h1>
    <ul class="list-unstyled mt-3 mb-4">
      <li><%= plan.space_allowed %> GB <%= t('pages.pricing.of_storage') %></li>
      <li>...</li>
      <li>...</li>
      <li>...</li>
    </ul>
    <%= form_tag(subscription_cart_path, method: :patch) do %>
      <%= hidden_field_tag("plan_id", plan.id) %>
      <%= submit_tag("Add to Cart", class: "btn btn-lg btn-block btn-outline-primary", id: "add-to-cart") %>
    <% end %>
  </div>
</div>

app/views/plans/_yearly_paid_plan.html.erb
<div class="col-4 mr-auto ml-auto">
  <div class="card mb-4 box-shadow">
    <div class="card-header">
      <h4 class="my-0 font-weight-normal"><%= yearly_paid_plan.name %></h4>
    </div>
    <div class="card-body">
      <%= image_tag("#{yearly_paid_plan.name.downcase}.png", alt: "#{yearly_paid_plan.name}_icon") %>
      <h1 class="card-title pricing-card-title">
        <%= humanized_money(yearly_paid_plan.price) %> &euro;<small class="text-muted">/año</small>
      </h1>
      <ul class="list-unstyled mt-3 mb-4">
        <li><%= yearly_paid_plan.space_allowed %> GB de almacenamiento</li>
        <li><br></li>
        <li><br></li>
        <li><br></li>
      </ul>
      <% if user_signed_in? %>
        <% if current_user.current_subscription.free? %>
          <%= link_to "Suscribirte", new_subscription_path(yearly_paid_plan.id), class: "btn btn-lg btn-block btn-outline-primary" %>
        <% else %>
          <% if current_user.current_plan?(yearly_paid_plan.id) %>
            <%= link_to "Estás suscrito", "#", class: "btn btn-lg btn-block btn-outline-primary disabled" %>
          <% else %>
            <%= link_to "No estás suscrito", "#", class: "btn btn-lg btn-block btn-outline-primary disabled" %>
          <% end %>
        <% end %>
      <% else %>
        <%= link_to "Suscribirte", new_user_session_path, class: "btn btn-lg btn-block btn-outline-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/plans/index.html.erb
<% provide(:title, "Precios") %>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">Precios</h1>
  <p class="lead">Elige el plan que mejor se adapte a ti</p>
</div>

<div class="container">
  <div class="row">
    <div class="col offset-5">
      <ul class="nav nav-pills" role="tablist">
        <li class="nav-item">
          <a class="nav-link active" data-toggle="pill" href="#monthly">Mensual</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-toggle="pill" href="#yearly">Anual</a>
        </li>
      </ul>
    </div>
  </div>
  <div class="tab-content">
    <div id="monthly" class="container tab-pane active"><br>
      <div class="card-deck mb-3 text-center">
        <%= render partial: "free_plan", object: @free_plan %>
        <%= render partial: "monthly_paid_plan", collection: @monthly_paid_plans %>
      </div>
    </div>
    <div id="yearly" class="container tab-pane fade"><br>
      <div class="card-deck mb-3 text-center">
        <%= render partial: "free_plan", object: @free_plan %>
        <%= render partial: "yearly_paid_plan", collection: @yearly_paid_plans %>
      </div>
    </div>
  </div>

</div>